apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  namespace: logging
  name: logging-elastic
spec:
  version: 7.4.2
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
    - name: logging-elastic
      count: 1
      podTemplate:
        spec:
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
              command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          containers:
            - name: elasticsearch
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms1536m -Xmx1536m"
              resources:
                requests:
                  memory: 2Gi
                  cpu: 0.5
                limits:
                  memory: 3Gi
                  cpu: 2
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 200Gi
            storageClassName: hdd-ssd
      config:
        node.master: true
        node.data: true
        node.ingest: true
        xpack.monitoring:
          collection.interval: 30s
          history.duration: 2d
        xpack.security.authc:
          realms:
            native:
              native1:
                order: -101
            file:
              file1:
                order: -100

---

apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  namespace: logging
  name: logging-kibana
spec:
  version: 7.4.2
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  count: 1
  elasticsearchRef:
    name: logging-elastic
  podTemplate:
    spec:
      containers:
        - name: kibana
          env:
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx1024m"
          resources:
            requests:
              memory: 1Gi
              cpu: 0.5
            limits:
              memory: 2Gi
              cpu: 2
